### ISSUE TITLE
AE2 World Gen Issue 

### ISSUE THREAD

**Issue by JensenButton9** [TeamAOF/All-of-Fabric-5#193] opened 2022-03-18 17:43 UTC
Bug / Issue:
I have found an issue where my world will freeze when attempting to generate and AE2 meteor, I have determined that this mod is the cause as the issue went away when I removed the mod during troubleshooting, and I have already made a report to the mod author , just thought that I should make you aware that this bug exists with this mod in the pack, at the time of writing, encase anyone else encounters a similar issue to me.

If you want to experience the bug firsthand generate a single player world, in version 1.0.1 with the seed -7336665869959619690, go to the coordinates, -3714 110 -12922, fly north across the river and then the world will hang attempting to generate an AE2 meteor at, -3735 74 -13475.

FYI:
During Testing to keep continuity between client and server setting I set the simulation distance to 8 and render to 10 . Prior to this I tested the mods: Ferrite Core, Lithium, Biome Makeover, oh the biomes you'll go, Lazy DFU, Mo structure, Magical Forest, Repurposed Structures, Null Things, Tower of the wild, Promonade, Better End, Better Stronghold, The Graveyard, Stoneholm.

Crash Log
https://gist.github.com/JensenButton9/6af0f38652c247ebe14b9229904c4749

**Comment by dandin87** [comment] 2022-03-18 18:47
This is interesting because we do get this crash from time to time on the servers. Mojang actually made a fix for this in the last snapshot.

[21w11a] Added server property max-chained-neighbor-updates to limit the amount of consecutive neighbor updates before skipping additional ones. Negative values remove the limit.

**Comment by dandin87** [comment] 2022-03-18 18:59
BTW, you can map logs here https://shartte.github.io/minecraft-mapper/
and then its more readable
https://aofpaste.com/nicewovuvu.sql

**Comment by dandin87** [comment] 2022-03-22 03:38
AE2 thought they managed to patch this bug, but seeing as vanilla made a special fix in the snapshots, its likely rooted in the vanilla code. 
A fix for this is to use C2ME mod which will make it not crash when generating this area. I tested this issue on another seed where they had the same crash, and the server did not crash. Only issue with C2ME is some massive log spam about initializing strongholds caused by an issue/conflict with the better strongholds mod. Aside from the log spam it does work though.

You will need to download this github actions build. as they only keep the latest file on curseforge.
https://github.com/RelativityMC/C2ME-fabric/suites/5372194438/artifacts/168579432

**Comment by JensenButton9** [comment] 2022-03-27 16:48
So, if I make use of this concurrent chunk generating mod it should alleviate the world generation crashes at the cost of increasing the size of the log files. A small price to pay, log files don't generally take up that much space anyway relative to the world size. I can easily get up to 10 Gb on a Modded world depending on the pack and whether it incentivizes exploration. From what I gather this mod is similar to the MCMT mod but for Fabric.  Also, that log mapper will be super useful for diagnosing issue in the future as I couldn't not understand what each of the numbers represented in the raw format hence process of elimination was the best option with mods that effect world gen. I was not aware such tools existed as Minecraft is not an Open-Source application.

**Comment by xxlio109** [comment] 2022-04-16 17:49
I had the same problem and it was solved using C2ME.

**Comment by JensenButton9** [comment] 2022-04-27 23:38
> I had the same problem and it was solved using C2ME.

And it makes the server run even smoother.

**Closed** 2022-08-16 04:07 UTC
Labels: Help wanted, Mod Issue
