### ISSUE TITLE
Industrial-Revolution April Fools Crash

### ISSUE THREAD

**Issue by McKitten** [TeamAOF/All-of-Fabric-5#222] opened 2022-03-31 21:06 UTC
Modpack version 1.1.1

https://github.com/GabrielOlvH/Industrial-Revolution/issues/434

Thought to try upgrading to 1.1.2 but  org.apache.commons.codec.digest.DigestUtils is crashing on the server.
Will try 1.1.2 with a rollback of that file (if i can figure out which) but IndRev is the same version.

**Comment by 8w-gremlin** [comment] 2022-03-31 21:06
Yeah, can confirm, this is happening to me too.

**Comment by 8w-gremlin** [comment] 2022-03-31 22:09
A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'kambrik'!
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:159)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'kambrik'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:157)
	... 2 more
Caused by: java.lang.ExceptionInInitializerError
	at io.ejekta.kambrik.internal.KambrikMod.idOf(KambrikMod.kt:30)
	at io.ejekta.kambrik.logging.KambrikMarkers.createIdMarker(KambrikMarkers.kt:16)
	at io.ejekta.kambrik.logging.KambrikMarkers.<clinit>(KambrikMarkers.kt:12)
	at io.ejekta.kambrik.internal.KambrikPrelaunch.handleCustomEntryData(KambrikPrelaunch.kt:31)
	at io.ejekta.kambrik.internal.KambrikPrelaunch.onPreLaunch(KambrikPrelaunch.kt:18)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 4 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2588 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_2960.<clinit>(class_2960.java:25)
	... 10 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
	... 14 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method owo(Ljava/lang/String;)Ljava/lang/String; in indrev.mixins.json:aprilfools.MixinTranslatableText from mod indrev failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap indrev-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 17 more

**Comment by GabrielOlvH** [comment] 2022-03-31 22:41
Updating to https://www.curseforge.com/minecraft/mc-mods/industrial-revolution/files/3725959 should fix this, sorry about this issue

**Comment by ImAK9** [comment] 2022-03-31 23:32
Fixed in 1.1.3

**Closed by ImAK9** 2022-03-31 23:32 UTC
