### ISSUE TITLE
enchantment combining in anvil is bugged

### ISSUE THREAD

**Issue by 800020h** [TeamAOF/All-of-Fabric-5#175] opened 2022-03-07 01:51 UTC
level n+level n=level max
it should equal level (n+1)

**Comment by dandin87** [comment] 2022-03-07 22:35
This is caused by adventureZ mod. If its not fixed by the next pack update, we will downgrade to the previous version which will fix this issue.

**Comment by yorii** [comment] 2022-03-11 00:52
It also causes the over-leveled enchants from goblin traders to be unusable, hopefully that will also be fixed.

**Closed** 2022-03-25 22:12 UTC
Labels: Fixed in next update
