### ISSUE TITLE
[Mod Suggestion] CC: Restitched

### ISSUE THREAD

**Issue by Just8Will** [TeamAOF/All-of-Fabric-5#248] opened 2022-04-19 18:13 UTC
CC Restitched is available for 1.18.1
Since open computers isn't available any more it would be great to get some on aof5.

https://github.com/cc-tweaked/cc-restitched

**Comment by SirEdvin** [comment] 2022-05-05 13:28
CC Restitched even available for 1.18.2 :)

**Comment by yorii** [comment] 2022-05-05 13:43
Duplicate of #93 
And already added in dev branch for the 1.18.2 release

**Comment by SirEdvin** [comment] 2022-05-05 13:44
:fireworks: :tada:

**Comment by dandin87** [comment] 2022-05-13 19:54
Added in pack version 1.2.0

**Closed by dandin87** 2022-05-13 19:54 UTC
