### ISSUE TITLE
[bug] Crashes on Mac

### ISSUE THREAD

**Issue by SubarcticPaper** [TeamAOF/All-of-Fabric-5#228] opened 2022-04-03 22:03 UTC
When trying to load the modpack on a mac it crashes. After uninstalling and reinstalling it will work for a a little bit but then crash again even when the game is running. Here is the crash report:

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 4/3/22, 5:57 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'kubejs'!
	at net.minecraft.class_310.mdaf11c9$lambda$invoke$4$1(class_310.java:7560)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.minecraft.class_310.mdaf11c9$lambda$invoke$5$0(class_310.java:7558)
	at net.minecraft.class_310.redirect$bad000$init(class_310.java:7524)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: There were startup script syntax errors! See logs/kubejs/startup.txt for more info
	at dev.latvian.mods.kubejs.fabric.KubeJSFabric.onInitialize(KubeJSFabric.java:18)
	at net.minecraft.class_310.mdaf11c9$lambda$init$1$4(class_310.java:7512)
	at net.minecraft.class_310.mdaf11c9$lambda$invoke$5$0(class_310.java:7556)
	... 10 more
Caused by: java.lang.RuntimeException: There were startup script syntax errors! See logs/kubejs/startup.txt for more info
	at dev.latvian.mods.kubejs.script.ScriptManager.load(ScriptManager.java:152)
	at dev.latvian.mods.kubejs.KubeJS.<init>(KubeJS.java:112)
	at dev.latvian.mods.kubejs.fabric.KubeJSFabric.onInitialize(KubeJSFabric.java:12)
	... 12 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_310.mdaf11c9$lambda$invoke$4$1(class_310.java:7560)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.minecraft.class_310.mdaf11c9$lambda$invoke$5$0(class_310.java:7558)
	at net.minecraft.class_310.redirect$bad000$init(class_310.java:7524)
	at net.minecraft.class_310.<init>(class_310.java:452)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Mac OS X (x86_64) version 12.2.1
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 967927192 bytes (923 MiB) / 1551892480 bytes (1480 MiB) up to 8422162432 bytes (8032 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 70 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel Iris Pro
	Graphics card #0 vendor: Intel
	Graphics card #0 VRAM (MB): 1536.00
	Graphics card #0 deviceId: 0x0d26
	Graphics card #0 versionInfo: Revision ID: 0x0008
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 16384.00
	Virtual memory used (MB): 8914.69
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 3 total; -Xss1M -Xmx8032m -Xms256m
	Fabric Mods: 
		additionaladditions: Additional Additions 3.0.1
		adorn: Adorn 3.3.1+1.18.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.4
		advancementplaques: Advancement Plaques 1.4.4
		advancements-enlarger: Advancements Enlarger 0.2.4
		advdebug: Advancements Debug 2.3.0
		adventurez: AdventureZ 1.4.7
		ae2: Applied Energistics 2 10.1.0-beta.2
		ae2things: AE2Things 1.0.2-beta.2
		ae2wtlib: AE2WTLib 10.1.1-beta.6
		ambientenvironment: Ambient Environment 7.0+17
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.18.1
		aofemotes: AOF Emotes 0.0.1
		appleskin: AppleSkin 2.3.0+mc1.18.1
		aqupdcaracal: Caracal mob 1.18-1.3.8
		arcanus: Arcanus 1.27
		architects_palette: Architect's Palette Fabric 1.6
		architectury: Architectury 3.7.37
		artifacts: Artifacts 6.0.0+fabric
		artifality: Artifality 0.5.5
		attributefix: AttributeFix 13.0.5
		authme: Auth Me 2.2.0
		autoconfig1u: Auto Config v1 Updated 3.4.0
		axolotlitemfix: Axolotl Item Fix 1.1.3
		balm-fabric: Balm 2.4.3+0
		bannerpp: Banner++ 2.0.4+mc.1.18-rc4
		basicaiots: Basic AIOTs 1.3.3+1.18.1
		bcc: BetterCompatibilityChecker fabric-1.0.5
		beaconoverhaul: Beacon Overhaul 1.5.0+1.18
		better_loading_screen: Better Loading Screen 1.4.0
		betterazalea: Better Azalea 1.0.1-SNAPSHOT
		betterdungeons: YUNG's Better Dungeons 1.18-1.0
		bettermineshafts: YUNG's Better Mineshafts 1.18.1-1.0
		bettermounthud: Better Mount HUD 1.1.4
		betterpingdisplay: Better Ping Display 1.1.1
		betterstrongholds: YUNG's Better Strongholds 1.18.1-1.0.1
		bewitchment: Bewitchment 1.18-15
		bhmenu: BHMenu-Fabric 1.17.1-1.18.2-1.3
		biomemakeover: Biome Makeover 1.18.1-1.4.8
		bitsandchisels: BitsAndChisels 2.6.4
		blast: BLAST 1.8.3
		blockus: Blockus 2.3.10+1.18.1
		blue_endless_jankson: jankson 1.2.1
		boatcontainer: BoatContainer 1.0.4
		bookshelf: Bookshelf 12.0.23
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.5-1.18
		botania: Botania 1.18.1-429-FABRIC
		bountiful: Bountiful 2.0.1
		bowinfinityfix: Bow Infinity Fix rv11
		breakprogress: Break Progress 1.0.1
		buildinggadgets: st'ructure tools 1.0.10
		builtinservers: Builtin Servers 1.0.1-BETA+1.18
		byg: BYG 1.3.5.13
		cacao: Croptopia's Chocolaterie 1.0
		campanion: Campanion 3.0.2
		camsbackpacks: Cammie's Wearable Backpacks 2.11
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.1.0
		capybara: Capybara 1.0.1
		cardinal-components-base: Cardinal Components API (base) 4.1.3
		cardinal-components-entity: Cardinal Components API (entities) 4.1.3
		cardinal-components-item: Cardinal Components API (items) 4.0.0
		cardinal-components-level: Cardinal Components API (world saves) 4.0.0
		cardinal-components-world: Cardinal Components API (worlds) 4.0.0
		carrier: Carrier 1.9.1
		catwalksinc: Catwalks Inc. 1.2.0
		chalk: Chalk 1.2.2
		cherishedworlds: Cherished Worlds 2.0.1-1.18
		chisel: Chisel Refabricated 1.4.5
		cleancut: CleanCut 1.18-4.0-fabric
		clienttweaks: Client Tweaks 7.1.0
		cloth-api: Cloth API 3.1.61
		cloth-armor-api-v1: Cloth Armor API v1 1.5.47
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 3.1.61
		cloth-common-events-v1: Cloth Common Events v1 3.1.61
		cloth-config: Cloth Config v6 6.2.57
		cloth-datagen-api-v1: Cloth Datagen v1 3.1.61
		cloth-scissors-api-v1: Cloth Scissors API v1 3.1.61
		cloth-utils-v1: Cloth Utils v1 3.1.61
		clumps: Clumps 8.0.0+5
		com_electronwill_night-config_core: core 3.6.5
		com_electronwill_night-config_toml: toml 3.6.5
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_github_luben_zstd-jni: zstd-jni 1.5.2-2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.1
		companion: Companion 1.2.1
		confabricate: confabricate 2.2.0-SNAPSHOT+4.1.1
		conjuring: Conjuring 1.0.20+1.18
		continuity: Continuity 1.1.0+1.18
		controlling: Controlling For Fabric 9.0+15
		couplings: Couplings 1.7.1+1.18
		craftingtweaks: Crafting Tweaks 13.0.0
		crawl: Crawl 0.10.2
		creeperoverhaul: Creeper Overhaul 0.3.0
		crookedcrooks: Crooked Crooks 2.0.1+1.18.1
		croptopia: Croptopia 1.8.3
		croptosis: Croptosis 1.4.2
		cyti: Can You Trash It? 1.0.3
		dankstorage: Dank Storage 1.18.1-3.5.4
		dark-enchanting: Dark Enchanting 0.6.3+1.18
		darkpaintings: DarkPaintings 9.0.3
		darkutils: DarkUtilities 9.0.2
		dashloader: DashLoader 3.1.1+1.18
		dawn: Dawn API 3.2.0
		deathlog: DeathLog 0.2.6+1.18
		decorative_blocks: Decorative Blocks 2.0.4
		deepslatecutting: Deepslate Cutting 1.3.1
		defaultoptions: Default Options 14.1.0
		dev_quantumfusion_dashloader_dashloader-core: dashloader-core 1.4.0
		dev_quantumfusion_hyphen: hyphen 0.2.0
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.4
		dml-refabricated: Deep Mob Learning: Refabricated 0.5.3-beta
		dml-refabricated-base: DML: Refabricated - Base 0.5.3-beta
		dml-refabricated-events: DML: Refabricated - Vanilla Events 0.5.3-beta
		dml-refabricated-modular-armor: DML: Refabricated - Glitch Armor 0.5.3-beta
		dml-refabricated-rei: DML: Refabricated - REI Integration 0.5.3-beta
		dmlsimulacrum: Deep Mob Learning: Simulacrum 0.5.3-beta
		dragonloot: DragonLoot 1.0.10
		dual_riders: DualRiders 1.0.5
		dusk: Dusk Mod 1.18-1.7
		dustrial_decor: Dustrial Decor 0.5
		dwarfcoal: Dwarf Coal 1.18.1-1.0.1
		dyed: Dyed 1.18.2-1.0.1
		dynamicfps: Dynamic FPS 2.1.0
		earthbounds: Earthbounds 1.0.5b
		ecologics: Ecologics 1.3.0
		eggtab: Egg Tab 2.2.0+1.18-fabric
		elytratrinket: Elytra Trinket 3.0.0-1.18.1
		enchdesc: EnchantmentDescriptions 9.0.13
		entitybanners: Entity Banners 1.0.2-BETA+1.18
		equipmentcompare: Equipment Compare 1.2.12
		expandability: ExpandAbility 5.0.0
		expandedstorage: Expanded Storage 7.3.10
		experiencebugfix: Experience Bug Fix 18
		extraalchemy: Extra Alchemy 1.7.0
		extragenerators: Extra Generators 1.1.2-BETA+1.18
		extremesoundmuffler: Extreme sound muffler 3.24_fabric-1.18.1
		fabric: Fabric API 0.46.6+1.18
		fabric-api-base: Fabric API Base 0.4.3+d7c144a8d2
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.3+d7c144a865
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a865
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.10+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a865
		fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a865
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.9+d7c144a865
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a865
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a865
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a865
		fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.7+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.9+d7c144a865
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.7+b4f4f6cd65
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.13+713c266865
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a865
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.7+d7c144a865
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.12+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.4+d7c144a865
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a865
		fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.5+737332ce65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.13+d7c144a865
		fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac65
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.11+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.15+6825030165
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+713c266865
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.15+8906aafd65
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.8+d7c144a865
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a865
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.3+d7c144a865
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.9+d7c144a865
		fabric-textures-v0: Fabric Textures (v0) 1.0.10+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.4.0-modified-technici4n+ea42e1b365
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.10+c329913d65
		fabricloader: Fabric Loader 0.13.3
		fake-player-api: Fake Player API 0.3.0
		farmersdelight: Farmer's Delight 1.18.1-0.2.0
		farmingforblockheads: Farming for Blockheads 9.0.3
		farsight: Farsight Mod 1.18-1.7
		fastfurnace: FastFurnace 1.18-4
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 1.0.1+1.18.1
		ferritecore: FerriteCore 4.1.2
		fiber: fiber 0.23.0-2
		floral_flair: Floral Flair 1.2.2
		forgeconfigapiport: Forge Config API Port 3.1.1
		ftbchunks: FTB Chunks 1801.3.4-build.127
		ftblibrary: FTB Library 1801.3.5-build.109
		ftbquests: FTB Quests 1801.3.7-build.97
		ftbteams: FTB Teams 1801.2.5-build.48
		ftbultimine: FTB Ultimine 1801.3.2-build.52
		gateofbabylon: Gate Of Babylon 1.6.0-1.18.1
		gbfabrictools: GBfabrictools 1.2.2+1.16
		geckolib3: Geckolib 3.0.33
		glassential: Glassential 1.3.0
		go-fish: Go Fish 1.4.1-1.18.1
		goblintraders: Goblin Traders 1.5
		goldenhoppers: Golden Hoppers 1.2.0
		goosik-config: goosik-config 0.2.0
		graveyard: The Graveyard 1.6
		graveyard_biomes: The Graveyard Biomes 1.0
		guardvillagers: Guard Villagers Fabric 1.18.1-1.0.11
		guild: Guild 0.3.8
		harvest_scythes: Harvest Scythes 2.4.1
		healthoverlay: Health Overlay 6.0.1
		horseinfo: Horse Info 0.4.1-1.18
		iceberg: Iceberg 1.0.38
		iknowwhatimdoing: I Know What I'm Doing 4.0.0
		impaled: Impaled 1.0.3
		impersonate: Impersonate 2.4.0
		improved-stations: Improved Stations 2.0.8
		incantationem: Incantationem 1.1.3+1.18.1
		indium: Indium 1.0.2-alpha3+mc1.18.1
		indrev: Industrial Revolution 1.13.8-BETA
		infusion_table: Infusion Table 1.0.5
		inmis: Inmis 2.5.1-1.18.1
		inventoryhud: Inventory HUD + 3.4.2
		inventorysorter: Inventory Sorter 1.8.5-1.18
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		iris: Iris 1.2.0-pre
		iron-jetpacks: Iron Jetpacks 0.4.3
		itemfilters: Item Filters 1801.2.6-build.16
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		jumpoverfences: JumpOverFences 1.16-0.0.3
		kambrik: Kambrik 3.0.1-1.18
		kanos_config: Kanos Config 0.1.5+1.14.4-1.18.2
		kibe: Kibe 1.9.6-BETA+1.18
		kjsextras: KubeJS Extras 1.5.0
		kleeslabs: KleeSlabs 11.0.0
		ktdatataglib: KtDataTagLib 1.6.4-1
		kubejs: KubeJS 1801.4.3-build.310
		kyrptconfig: Kyrpt Config 1.3.9-1.18
		lazydfu: LazyDFU 0.1.2
		legendarytooltips: Legendary Tooltips 1.2.4
		libblockattributes_core: LibBlockAttributes (Core) 0.10.0
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.10.0
		libblockattributes_items: LibBlockAttributes (Items) 0.10.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 5.3.0+1.18
		libninepatch: LibNinePatch 1.1.0
		lifts: Lifts 1.4-BETA+1.18
		lightoverlay: Light Overlay 6.0.4
		lithium: Lithium 0.7.8
		logprot: Logprot Mod 1.18-1.5
		lovely_snails: Lovely Snails 1.0.3+1.18
		lumiwool: Luminous Wool 1.2.2
		maelstrom_library: Maelstrom Library 1.2.3-1.18-rc3
		magicalforest: Magical Forest 2.0.1
		magna: Magna 1.7.0-1.18-pre1
		maybe-data: Maybe data 1.0.1-1.17
		maybe-more-data: Maybe More Data 1.0.0-1.18.1
		mcdict: MCDict 2.1.0+1.17.1
		mcwfences: Macaw's Fences and Walls 1.0.4
		mcwlights: Macaw's Lights and Lamps 1.0.2
		mcwpaintings: Macaw's Paintings 1.0.2
		mcwtrpdoors: Macaw's Trapdoors 1.0.4
		megane: megane 7.1.3
		megane-api: megane-api 7.0.0
		megane-applied-energistics-2: megane-applied-energistics-2 7.0.1
		megane-deep-mob-learning-simulacrum: megane-deep-mob-learning-simulacrum 7.0.0
		megane-extra-generators: megane-extra-generators 7.0.0
		megane-fabric-transfer: megane-fabric-transfer 7.0.0
		megane-industrial-revolution: megane-industrial-revolution 7.0.0
		megane-kibe: megane-kibe 7.0.0
		megane-lib-block-attributes: megane-lib-block-attributes 7.0.0
		megane-reborn-core: megane-reborn-core 7.0.0
		megane-reborn-energy: megane-reborn-energy 7.0.0
		megane-runtime: megane-runtime 7.1.3
		megane-tech-reborn: megane-tech-reborn 7.0.0
		megane-vanilla: megane-vanilla 7.0.0
		megane-wireless-networks: megane-wireless-networks 7.0.0
		minecarttweaks: Cammie's Minecart Tweaks 1.2
		minecraft: Minecraft 1.18.1
		mm: Manningham Mills 2.3
		mobscarecrow: Mob Scarecrow 1.2.0
		mocolors: Mo' Colors 1.3.0
		modern_industrialization: Modern Industrialization 1.0.5
		modmenu: Mod Menu 3.0.1
		moretags: More Tags 2.0.3
		morevillagers-fabric: MoreVillagersFabric 3.1.1-SNAPSHOT
		mostructures: Mo' Structures 1.3.0-pre1+1.18
		mousetweaks: Mouse Tweaks 2.22
		mtmechs: Magitek Mechs 1.0.11
		multipart_entities: MultipartEntities 1.1.4-1.18-rc3
		myron: Myron 1.6.2+1.18.1
		mythic-mounts: Mythic Mounts 1.18-5.0
		naturescompass: Nature's Compass 1.18.1-2.0.3-fabric
		nears: Nears 1.1.2
		netherportalfix: NetherPortalFix 9.0.0
		ninjaphenix_container_lib: NinjaPhenix's Container Library 1.3.0
		no_null_processors: No Null Processors - Fabric 2.0.1+1.18.1
		noanglebrackets: NoAngleBrackets 1.1.0
		omega-config: OmegaConfig 1.2.3-1.18.1
		onastick: On A Stick 2.0.0
		openloader: OpenLoader 11.0.4
		opitems: Op Items 1.2.1
		org_anarres_jcpp: jcpp 1.4.14
		org_codehaus_groovy_groovy: groovy 3.0.8
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.8
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
		org_spongepowered_configurate-gson: configurate-gson 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		overloadedarmorbar: Overloaded Armor Bar 1.18.1-6
		owo: oωo 0.5.2+1.18
		patchouli: Patchouli 1.18.1-65-FABRIC
		pehkui: Pehkui 3.2.1+1.14.4-1.19
		phosphor: Phosphor 0.8.1
		pigpen: PigPen 7.0.2
		platforms: Platforms 1.2.1
		playerabilitylib: Pal 1.5.0
		pling: Pling 1.5.0
		plushies: Plushie Mod 1.2
		promenade: Promenade 2.5.1
		questsadditions: Quests Additions 1.2.0
		quickshulker: Quick Shulker 1.3.6-1.18
		raised: Raised 1.18.2-1.0.4
		rare-ice: Rare Ice 0.4.0
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.1.0
		redstonebits: Redstone Bits 1.7.0
		replanter: Replanter 1.3
		repurposed_structures: Repurposed Structures 3.3.12+1.18.1
		respawnablepets: Respawnable Pets 1.18-2
		rhino: Rhino 1801.1.9-build.131
		rightclickharvest: Right Click Harvest 1.5.1
		roughlyenoughitems: Roughly Enough Items 7.3.443
		roughlyenoughresources: Roughly Enough Resources 2.4.1
		runelic: Runelic 10.0.6
		secretrooms: Secret Rooms 1.3.0+1.18.1
		shetiphiancore: ShetiPhianCore 1.2.4
		shulkerboxtooltip: Shulker Box Tooltip 3.0.5+1.18
		shulkerutils: shulkerutils 1.0.4-1.18
		simpleteleporters: Simple Teleporters 2.3.0
		slight-gui-modifications: 'Slight' GUI Modifications 2.0.3
		slimyfloor: Slimy Floor 1.18-1.2.2
		slotlock: SlotLock 1.0.4-BETA+1.18
		smootherbedrock: Smoother Bedrock 1.0.4
		smwyg: Show Me What You Got 1.0.0
		sodium: Sodium 0.4.0-alpha6+build.14
		someforgepatchesported: Some Forge Patches Ported 1.0.2
		spark: spark 1.8.6
		spectrum: Spectrum 1.2.13-1.18.1-midgame14-trinkets-brewing
		stacc: Stacc 1.2.3
		staffofbuilding: Staff of Building 1.4.1-1.18.1
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.4.2
		strawdummy: Straw Dummy 1.6.0
		team_reborn_energy: Energy 2.2.0
		techreborn: Tech Reborn 5.1.0
		terrablender: TerraBlender 1.1.0.77
		terraform-shapes-api-v1: Terraform Shapes API (v1) 2.1.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		terrarianslimes: Terrarian Slimes 1.1-BETA+1.18
		thatched: Thatched 1.0.2
		thonkutil-base: ThonkUtil Base 1.5.1+31ad4eb1c8
		thonkutil-capes-v1: ThonkUtil Capes (v1) 1.2.2+befce073c8
		thonkutil-potions-v0: ThonkUtil Potions (v0) 1.3.1+befce073c8
		thonkutil-trades-v1: ThonkUtil Trades (v1) 1.1.8+d77526a2c8
		toolstats: ToolStats 8.0.6
		tooltipfix: ToolTip Fix 1.0.4-1.18
		totemmod: Wither Totems Mod 0.3.4-1.18-rc2
		towers_of_the_wild_reworked: Towers of the Wild: Reworked 2.2.0
		transportables: Transportables 1.1
		trapexpansion: Trap Expansion 1.3.3
		trashslot: TrashSlot 11.0.2
		trinkets: Trinkets 3.2.1
		twigs: Twigs 1.1.2
		urns: Urns 1.0.1
		vanilla-hammers: Vanilla Hammers 3.2.0-1.18.1
		vanillaexcavators: Vanilla Excavators 1.1.0
		villager-hats: Villager Hats Mod 1.3.1
		visuality: Visuality 0.4.1
		waystones: Waystones 2.4.1
		wirelessnetworks: Wireless Networks 1.4.1
		wmitaf: WMITAF 2.2.0
		wolveswitharmor: Wolves With Armor 1.7.0-1.18
		wthit: wthit 4.5.5
		xlpackets: XLPackets 2.1-1.17.1
		xps: Xp Obelisk 0.3.3.r_for_1.18.x_Fabric
		yigd: You're in Grave Danger 1.2.22
		yungsapi: YUNG's API 1.18-Fabric-36
		yungsbridges: YUNG's Bridges 1.18.1-1.0
		yungsextras: YUNG's Extras 1.18.1-1.0
	Launched Version: fabric-loader-0.13.3-1.18.1
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by ImAK9** [comment] 2022-04-04 08:41
duplicate of #227

**Comment by SubarcticPaper** [comment] 2022-04-04 16:39
I have uninstalled Better loading screens mod and I still have this issue. It is also not the same issue as #227. With this issue I am not able to load the modpack at all.

**Comment by SubarcticPaper** [comment] 2022-04-04 16:53
The startup.txt had this:

[12:35:14] [INFO ] Loaded script startup_scripts:aof5_logo 2.js in 0.088 s
[12:35:14] [INFO ] Loaded script startup_scripts:worldgen 2.js in 0.002 s
[12:35:14] [INFO ] Loaded script startup_scripts:aof5_logo.js in 0.001 s
[12:35:14] [ERR  ] Error loading KubeJS script: TypeError: TypeError: redeclaration of const ORES_TO_REMOVE.
[12:35:14] [INFO ] Loaded 3/4 KubeJS startup scripts in 0.335 s

**Comment by SubarcticPaper** [comment] 2022-04-06 22:36
> Could you send me the logs/kubejs/startup.txt

Is there any update on this yet? I just wanted to make sure I sent the right thing

**Comment by ImAK9** [comment] 2022-04-10 17:01
That’s the correct file, gonna try to track it down tonight.

**Closed** 2022-05-16 19:17 UTC
