### ISSUE TITLE
[BUG] Origins compatibility 

### ISSUE THREAD

**Issue by RatsBats1** [TeamAOF/All-of-Fabric-5#238] opened 2022-04-12 21:29 UTC
When I was trying to add origins to AoF5 for a server for my friends, every time I would start the game, it would crash and mess with my pc. I have double checked the game versions but all of them are rated for 1.18.1 . I do have other mods installed including https://www.curseforge.com/minecraft/mc-mods/origins-classes/files , https://www.curseforge.com/minecraft/mc-mods/extra-origins/files and https://www.curseforge.com/minecraft/mc-mods/extra-classes-origins/files . From what I have looked into, it seems to be a AoF5 issue, however if it is a client issue, those that can help me please do. Thank you.
-Rats

**Comment by dandin87** [comment] 2022-04-12 21:43
Origins is not compatible with the modpack. One of the reason is the 1.18.1 version spectrum conflicts with it, but there are likey other conflicts. Spectrum has this conflict resolved in 1.18.2 so the next pack update, which is 1.18.2, may work with origins, but no guarantees. We do know it's something very many would like to add without issues and hopefully we can resolve that with the update to 1.18.2

**Comment by DaFuqs** [comment] 2022-04-15 06:55
confirmed to work with next Origins update

**Comment by RatsBats1** [comment] 2022-04-15 13:15
Thank you for the information. I will be looking forward to the next update, and will continue to use this mod pack for the time being

**Closed** 2022-04-15 13:16 UTC
