### ISSUE TITLE
[Mod Removal] AE2Things

### ISSUE THREAD

**Issue by yorii** [TeamAOF/All-of-Fabric-5#123] opened 2022-01-23 18:15 UTC
I would like to petition for the removal of AE2Things:
https://www.curseforge.com/minecraft/mc-mods/ae2things

It teaches bad AE2 practice to players, and doesn't actually serve any purpose other than to lower the difficulty level since everything it does can be replicated with barebone AE2.

At the bare minimum the storage disks it adds should be disabled, since they're practically cheaty creative mode items.

**Comment by k3nw4y** [comment] 2022-01-23 18:44
Or a late game recpie for it

**Comment by yorii** [comment] 2022-01-23 18:52
yeah a complete rebalance of the recipes would be a good option too

**Comment by Demsli** [comment] 2022-01-23 19:15
"At the bare minimum storage disks should be disabled". All the mod currently does is adding those disks. And what is a bad AE2 practice? I have been playing since 1.2.5 and it`s the first time I am hearing this. Players should do whatever they want, without any restrictions, it`s a sandbox game afterall. A bit harder recipes? Yeah, reasonable, but not for all disks. 1K disk can stay vanilla I think. Cause in original AE2 everyone skips 1K and goes to 4K. That way 1K AE2T typeless disk can find a purpose.

**Comment by Monster-Zer0** [comment] 2022-01-23 20:12
![](https://github.trello.services/images/mini-trello-icon.png) [card](https://trello.com/c/grOI77HA/25-card)

**Comment by IcyJalapeno** [comment] 2022-01-23 20:56
Can confirm 100%, Item Duplication is possible with the AE2Things Disk. 

- (1) Normal AE2 Storage Cell with stuff inside
- (1) AE2Things Disk

1. Place Normal AE2 Storage Cell top left inside the ME Drive, with anything you want duped.
2. Place AE2Thing Disk Drive in the bottom right inside the ME Drive (It doesn't show the drive is installed)
3. Check Crafting Terminal
4. Remove Normal AE2 Storage Cell top left inside the ME Drive
5. Check Crafting Terminal (Everything should be inside)
6. Notice ME Drive has a ghost copy of the Normal AE2 Storage Cell *will vanish when the ghost drive is empty*
7. Remove AE2Thing Disk Drive in the bottom right inside the ME Drive
8. Check Crafting Terminal (Everything should be inside)
9. Empty Crafting Terminal (ME Drive should be empty)
10. Destroy ME Drive
11. Replace ME Drive
12. Replace Normal AE2 Storage Cell top left inside the ME Drive, with anything you want duped.

**Comment by Demsli** [comment] 2022-01-23 20:58
> Can confirm 100%, Item Duplication is possible with the AE2Things Disk.
> 
> * (1) Normal AE2 Storage Cell with stuff inside
> * (1) AE2Things Disk
> 
> 1. Place Normal AE2 Storage Cell top left inside the ME Drive, with anything you want duped.
> 2. Place AE2Thing Disk Drive in the bottom right inside the ME Drive (It doesn't show the drive is installed)
> 3. Check Crafting Terminal
> 4. Remove Normal AE2 Storage Cell top left inside the ME Drive
> 5. Check Crafting Terminal (Everything should be inside)
> 6. Notice ME Drive has a ghost copy of the Normal AE2 Storage Cell _will vanish when the ghost drive is empty_
> 7. Remove AE2Thing Disk Drive in the bottom right inside the ME Drive
> 8. Check Crafting Terminal (Everything should be inside)
> 9. Empty Crafting Terminal (ME Drive should be empty)
> 10. Destroy ME Drive
> 11. Replace ME Drive
> 12. Replace Normal AE2 Storage Cell top left inside the ME Drive, with anything you want duped.

I think you should post it not here, but in a separeate issue post in "Issues" category.

**Comment by ProjectET** [comment] 2022-01-24 03:28
> Can confirm 100%, Item Duplication is possible with the AE2Things Disk.
> 
>     * (1) Normal AE2 Storage Cell with stuff inside
> 
>     * (1) AE2Things Disk
> 
> 
>     1. Place Normal AE2 Storage Cell top left inside the ME Drive, with anything you want duped.
> 
>     2. Place AE2Thing Disk Drive in the bottom right inside the ME Drive (It doesn't show the drive is installed)
> 
>     3. Check Crafting Terminal
> 
>     4. Remove Normal AE2 Storage Cell top left inside the ME Drive
> 
>     5. Check Crafting Terminal (Everything should be inside)
> 
>     6. Notice ME Drive has a ghost copy of the Normal AE2 Storage Cell _will vanish when the ghost drive is empty_
> 
>     7. Remove AE2Thing Disk Drive in the bottom right inside the ME Drive
> 
>     8. Check Crafting Terminal (Everything should be inside)
> 
>     9. Empty Crafting Terminal (ME Drive should be empty)
> 
>     10. Destroy ME Drive
> 
>     11. Replace ME Drive
> 
>     12. Replace Normal AE2 Storage Cell top left inside the ME Drive, with anything you want duped.

Unable to replicate on server or client

**Comment by IcyJalapeno** [comment] 2022-01-25 19:29
> > Can confirm 100%, Item Duplication is possible with the AE2Things Disk.
> > ```
> > * (1) Normal AE2 Storage Cell with stuff inside
> > 
> > * (1) AE2Things Disk
> > 
> > 
> > 1. Place Normal AE2 Storage Cell top left inside the ME Drive, with anything you want duped.
> > 
> > 2. Place AE2Thing Disk Drive in the bottom right inside the ME Drive (It doesn't show the drive is installed)
> > 
> > 3. Check Crafting Terminal
> > 
> > 4. Remove Normal AE2 Storage Cell top left inside the ME Drive
> > 
> > 5. Check Crafting Terminal (Everything should be inside)
> > 
> > 6. Notice ME Drive has a ghost copy of the Normal AE2 Storage Cell _will vanish when the ghost drive is empty_
> > 
> > 7. Remove AE2Thing Disk Drive in the bottom right inside the ME Drive
> > 
> > 8. Check Crafting Terminal (Everything should be inside)
> > 
> > 9. Empty Crafting Terminal (ME Drive should be empty)
> > 
> > 10. Destroy ME Drive
> > 
> > 11. Replace ME Drive
> > 
> > 12. Replace Normal AE2 Storage Cell top left inside the ME Drive, with anything you want duped.
> > ```
> 
> Unable to replicate on server or client
https://youtu.be/PzPjYYfNNYo

**Comment by ProjectET** [comment] 2022-01-25 20:34
Still unable to reproduce, could you try this in another chunk and use a regular me drive instead of a ae2things DISK?

**Comment by IcyJalapeno** [comment] 2022-01-26 20:00
> Still unable to reproduce, could you try this in another chunk and use a regular me drive instead of a ae2things DISK? If you are unable to reproduce it with the ae2 cell try it with the ae2things disk. If still unable to reproduce go to original location and use regular ae2 cell

ummmm, I need the AE2 ME Drive, so two storage disk can go into the system. Did you meant-  try moving to another chunk and use (2) AE2 Storage Cells, instead (1) of each AE2 Cell and AE2Things Disk ? The issue is the AE2Things Disk, which doesn't register correctly with AE2.

**Comment by IcyJalapeno** [comment] 2022-01-26 21:11
https://youtu.be/oflxufckk8E

Just Moved to a different chunk with (1) AE2 Storage Cell, (1) AE2Things Disk. Dup'ing is still possible.

**Comment by IcyJalapeno** [comment] 2022-01-26 23:11
I think I figured it out. When (1) AE2things Disk get partitioned by (1) AE2 Cell Workbench with something (did cobblestone in video, tried other things off video) the AE2things Disks becomes glitched. The Glitch state of the AE2things disk allows the dup'ing of what is ever inside the ME System at the time. 

https://youtu.be/7p-H1bPmUE8

**Comment by ProjectET** [comment] 2022-01-27 08:51
> I think I figured it out. When (1) AE2things Disk get partitioned by (1) AE2 Cell Workbench with something (did cobblestone in video, tried other things off video) the AE2things Disks becomes glitched. The Glitch state of the AE2things disk allows the dup'ing of what is ever inside the ME System at the time.
> 
> https://youtu.be/7p-H1bPmUE8

Thanks im able to reproduce that, ill get onto fixing that now

**Comment by ProjectET** [comment] 2022-01-27 12:23
Fixed in https://github.com/ProjectET/AE2Things/commit/6bafbe6697861cfaffb4ed9b80ba4d5ec131d7fe
Released the fix on curseforge

**Closed** 2022-02-28 04:07 UTC
