### ISSUE TITLE
Botania Mana Pylons don't work with Enchanting Table

### ISSUE THREAD

**Issue by MichaelBrandon** [TeamAOF/All-of-Fabric-5#142] opened 2022-02-01 22:21 UTC
Placed Mana Pylons next to enchanting table in accordance with Botania mod. 

Expected Result: Allow for tier three enchantments without the need for any book cases.
Actual Result: There appears to be no interaction between the mana pylon and the enchanting table.

**Comment by Hubry** [comment] 2022-02-02 01:36
What pack version? There was a similar issue to this that was caused by BCLib and was fixed on their side.

**Closed** 2022-02-28 04:05 UTC
